In [1]:
# Cluster news articles into topics
# using TF-IDF word frequency
# vectors.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("news_articles_kmeans_dataset.csv")

In [4]:
df.head()

,article_id,tfidf_1,tfidf_2,tfidf_3,tfidf_4,tfidf_5,tfidf_6,tfidf_7,tfidf_8,tfidf_9,...,tfidf_11,tfidf_12,tfidf_13,tfidf_14,tfidf_15,tfidf_16,tfidf_17,tfidf_18,tfidf_19,tfidf_20
0,A0001,0.217,0.948,0.163,0.113,0.088,0.705,0.578,0.368,0.211,...,0.239,0.636,0.903,0.311,0.515,0.570,0.418,0.024,0.294,0.096
1,A0002,0.661,0.923,0.506,0.465,0.225,0.318,0.126,0.447,0.859,...,0.978,0.877,0.286,0.081,0.255,0.231,0.183,0.621,0.983,0.135
2,A0003,0.199,0.301,0.488,0.448,0.611,0.136,0.423,0.088,0.122,...,0.764,0.912,0.078,0.805,0.266,0.008,0.313,0.110,0.351,0.771
3,A0004,0.013,0.610,0.160,0.341,0.548,0.848,0.393,0.051,0.049,...,0.787,0.525,0.105,0.399,0.515,0.702,0.329,0.873,0.724,0.630
4,A0005,0.500,0.512,0.712,0.306,0.407,0.438,0.649,0.906,0.881,...,0.061,0.043,0.893,0.642,0.053,0.486,0.045,0.232,0.313,0.668

In [5]:
X = df.drop('article_id',axis=1)

In [6]:
from sklearn.cluster import KMeans

In [7]:
model = KMeans(n_clusters=3)

In [8]:
df['cluster'] = model.fit_predict(X)

In [9]:
df.head()

,article_id,tfidf_1,tfidf_2,tfidf_3,tfidf_4,tfidf_5,tfidf_6,tfidf_7,tfidf_8,tfidf_9,...,tfidf_12,tfidf_13,tfidf_14,tfidf_15,tfidf_16,tfidf_17,tfidf_18,tfidf_19,tfidf_20,cluster
0,A0001,0.217,0.948,0.163,0.113,0.088,0.705,0.578,0.368,0.211,...,0.636,0.903,0.311,0.515,0.570,0.418,0.024,0.294,0.096,1
1,A0002,0.661,0.923,0.506,0.465,0.225,0.318,0.126,0.447,0.859,...,0.877,0.286,0.081,0.255,0.231,0.183,0.621,0.983,0.135,0
2,A0003,0.199,0.301,0.488,0.448,0.611,0.136,0.423,0.088,0.122,...,0.912,0.078,0.805,0.266,0.008,0.313,0.110,0.351,0.771,0
3,A0004,0.013,0.610,0.160,0.341,0.548,0.848,0.393,0.051,0.049,...,0.525,0.105,0.399,0.515,0.702,0.329,0.873,0.724,0.630,2
4,A0005,0.500,0.512,0.712,0.306,0.407,0.438,0.649,0.906,0.881,...,0.043,0.893,0.642,0.053,0.486,0.045,0.232,0.313,0.668,0

In [10]:
sample = [[0.5]*20]

In [11]:
model.predict(sample)

C:\Users\jiyam\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(

array([2], dtype=int32)